site_name: Cursus Databases
site_description: Leren werken databases om perfomante informatiesystemen te bouwen
site_author: Stijn Vercammen
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: teal
      accent: orange
nav:
  - Home: index.md
  - Inleiding: inleiding.md
  - Relationele modellen: relationele_modellen.md
  - ER-diagrammen: er_diagrammen.md
  - SQL basis: sql_basis.md
  - Joins: joins.md
  - Normalisatie: normalisatie.md
  - Indexen en performantie: indexen_performantie.md
  - Transacties: transacties.md
  - Praktijkcases: praktijkcases.md
markdown_extensions:
  - codehilite
  - admonition
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
plugins:
  - search
  - print-site
extra_css:
  - overrides.css